# Generated by Django 3.2.5 on 2021-08-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
