# Generated by Django 3.2.5 on 2021-08-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_image_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
