# Generated by Django 3.2.5 on 2021-08-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='test2',
            field=models.CharField(default=True, max_length=250),
        ),
    ]
