# Generated by Django 3.2.5 on 2021-08-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_alter_job_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
