# Generated by Django 3.2.5 on 2021-08-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0022_applicant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='image',
        ),
    ]
