# Generated by Django 3.2.5 on 2021-08-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0024_remove_job_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
